### ISSUE TITLE
pstree_v2 in splunkbase

### ISSUE THREAD

**Issue by 1ntrcpt0r** [murchisd/splunk_pstree_app#10]
Hi, 

will pstree_v2 be available as splunkbase app any time soon? The current version available still has the recursion depth problem and installing an app from file is not possible in Splunk Cloud.

**Comment by murchisd** [comment]
I've uploaded pstree 2.0.0 to Splunkbase it is currently pending review I will leave comment here once it has been approved

**Comment by murchisd** [comment]
Pstree 2.0.0 has been approved for Splunk Cloud. You should be able to install now. Let me know if any issues
