### ISSUE TITLE
Line 115

### ISSUE THREAD

**Issue by spitzd** [murchisd/splunk_pstree_app#2]
Hi,

I run into this error when I use the pstree command against my EDR data. Wondering if you could point me in the right direction. 

KeyError at "/opt/splunk/etc/apps/splunk_pstree_app/bin/pstree.py", line 115 : 'parent_process_name'

Many Thanks,
Denver

**Comment by spitzd** [comment]
FYI, I should point out that I only face that issue when running the simple search
index=edr category="AdvancedHunting-DeviceProcessEvents" 
| pstree child=process_name parent=parent_process_name
| table tree

However, when I run the detailed version as below, I don't have any issues and all works as expected. 
index=edr category="AdvancedHunting-DeviceProcessEvents" 
| eval parent = parent_process_name." (".parent_process_id.")"
| eval child = process_name." (".process_id.")"
| eval detail=strftime(_time,"%Y-%m-%d %H:%M:%S")." ".cmdline
| pstree child=child parent=parent detail=detail spaces=50
| table tree

Just thought I'd make you aware of it.. 

Thanks again.

**Comment by murchisd** [comment]
Hey Denver,

Thanks for bringing this to my attention! Can you provide some information on the log format you are running the search against (JSON, XML, etc.)? As far as I can tell right now this appears to be an issue with how Splunk passes the records to the search command.

For AutoKV formats, like XML and JSON only fields explicitly referenced in the previous parts of the search are added as a key in the OrderedDict for the event. Everything else would need to be parsed out of the _raw field passed to the command.

The simple solution for now is to add "| fields *" right before piping to the pstree command. This will create a key for all parsed fields. I am updating README example to include this.

I will keep looking in to this and see if there is a way to force Splunk to pass all auto extracted fields as a key in the dict.

**Comment by spitzd** [comment]
Hi Donald,

Apologies for the late reply. I am running this against MS Defender EDR data which is in JSON format. As you rightly suggested, using | fields gets around this problem. 

index=edr category="AdvancedHunting-DeviceProcessEvents" 
| fields process_name, parent_process_name 
| pstree child=process_name parent=parent_process_name
| table tree

You can go ahead and close this issue tbh since using the fields command is best practice to improve search performance anyway.  

Thanks again!

**Comment by murchisd** [comment]
No worries, thanks for the reply, closing issue
